// Auto-generate DG operation records on server startup
import { prisma } from "@/lib/prisma"

let isInitialized = false

export async function initializeAutoGeneration() {
  // Only run once per server session
  if (isInitialized) return
  isInitialized = true

  try {
    // Get today's date at midnight (for checking existing records)
    const todayMidnight = new Date()
    todayMidnight.setHours(0, 0, 0, 0)
    
    const tomorrow = new Date(todayMidnight)
    tomorrow.setDate(tomorrow.getDate() + 1)
    
    // Check if there are any records for today
    const existingRecords = await prisma.dGOperation.findMany({
      where: {
        date: {
          gte: todayMidnight,
          lt: tomorrow,
        },
      },
    })
    
    // If no records exist for today, create auto-generated records for each shift
    if (existingRecords.length === 0) {
      console.log('No records found for today. Creating auto-generated entries...')
      
      // Get a system user (or create a fallback)
      let systemUser = await prisma.user.findFirst({
        where: {
          role: 'TA' // Using TA as system user
        }
      })
      
      // If no user exists, we'll need to handle this
      if (!systemUser) {
        console.warn('No system user found. Auto-generated records will be created with first available user.')
        systemUser = await prisma.user.findFirst()
      }
      
      if (systemUser) {
        const shifts = ['M/S']
        
        for (const shift of shifts) {
          // Use current time when creating the record
          const now = new Date()
          
          await prisma.dGOperation.create({
            data: {
              date: now,
              shift: shift,
              isAutoGenerated: true,
              createdBy: systemUser.id,
              dutyStaffId: systemUser.id,
              digitalSignatureDutyStaff: 'System Auto-Generated',
              dutyStaffSignedAt: new Date(),
            },
          })
        }
        
        console.log('Auto-generated records created successfully for all shifts.')
      } else {
        console.error('Cannot create auto-generated records: No users in system')
      }
    } else {
      console.log('Records already exist for today. Skipping auto-generation.')
    }
  } catch (error) {
    console.error('Error creating auto-generated records:', error)
  }
}
